export const defaultProjects = [
  
  'Projects Casing durability',
  'RFID',
  'PID',
  'TREEL TT',
  'TREEL TL',
  'Accelerated testing',
  'Training',
  'Bald',
  'Mold',
  '9.00R20 field testing'
];
export const defaultPeople = ['Alex Chen', 'Morgan Diaz', 'Priya Kapoor'];
export const defaultMilestones = [
  
  'Initiate NDR Review Process',
  'Start Business case review & approval - Gate 1',
  'Start Detailed design review - Gate 2 sign off',
  'Start Proto sign off - Gate 3 sign off',
  'Start FDR / PRN - Gate 4',
  'Market feedback - Gate 5'
];
export const defaultActivities = [
  
  'VOC - Market research',
  'VOC - Historical Warranty & Quality Information.',
  'VOC - Team experience',
  'CFT formation',
  'Customer inputs - CFT visit',
  'Business Plan / Marketing Strategy.',
  'Benchmark identification',
  'Primary feasibility study',
  'Business case preparation',
  'Capex approval',
  'Timing chart preparation & alignment- PQPTC',
  'Preliminary product benchmarking',
  'Build house of quality (QFD)',
  'Concept preparation',
  'Concept review & sign off',
  'Project cover sheet & DVP input',
  'Prepare DFMEA',
  'Manufacturing Feasibility sign off input (tyre & other accessories)',
  'Manufacturing Feasibility sign off from plant',
  'Risk analysis',
  'Feasibility & risk assessment review',
  'Final RACE approval with WBS number',
  'Preparation of basic design',
  'Basic design review',
  'Detailed design & simulation',
  'Review of simulation results',
  'Preparation of engineering drawings & sign off',
  'Create PR',
  'PR approval',
  'Mold drawings to vendor for quotation',
  'Vendor selection, negotiation & P.O release',
  'Mold drawings to vendor for manufacturing',
  'Model inspection',
  'Creation of product code',
  'Design specification preparation - proto run',
  'Manufacturing spec preparation - proto run',
  'Building & curing preparation - proto run',
  'BOM / Routing',
  'Costing',
  'NDP update in system & product code extension',
  'PFMEA preparation',
  'Mold preparation',
  'Mold inspection & clearance before dispatch',
  'Mold transit to plant',
  'Mold inspection & release',
  'Proto run',
  'Design validation (DVP) - Plant',
  'Design validation (DVP) - Hasetri',
  'Compilation of proto results',
  'Review of proto results',
  'Homologation input',
  'Issue packaging specification',
  'Sample submission',
  'Issue design specification for pre-launch',
  'Issue manufacturing specification for pre-launch',
  'Issue process specification',
  'Issue of building & curing spec for pre-launch',
  'Pilot production validation (DVP) - Plant',
  'Pilot production validation (DVP) - HASETRI',
  'Review of Pilot production results',
  'PTG test request (creation & approval)',
  'PTG test plan (creation & approval)',
  'Dispatch of test tyres',
  'Fitment of test tyres',
  'Review of field evaluation results - 1',
  'Review of field evaluation results - 2',
  'Review of field evaluation results - 3',
  'Review of field evaluation results - 4',
  'Review of field evaluation results & closure',
  'Pre launch production',
  'Pre launch production results sign off - CPI gate 3',
  'Preparation of mold ramp up plan',
  'Release for commercial production',
  'Prepare PPAP & production control plan',
  'Preparation product launch',
  'Capture Post release feedback'
];
console.log('Activities from import:', defaultActivities);
